@startuml
UserApplicationService x--> UserData: 返却データ生成
UserApplicationService x--> User: 値を利用する
UserApplicationService x--> IUserRepository: ユーザ情報を取得
IUserRepository .> User: 値の依存
User <. UserData: 値の依存

class User {
  - userName: UserName
  - userId: UserId
}
class UserData {
  - userName: string
  - userId: string
  + get userName(): string
  + get userId(): string
}
note right
DTO
endnote

class UserApplicationService {
  - userRepository: IUserRepository
  + get(userName: string): UserData
}
interface IUserRepository {
  find(id: UserId): User
  find(name: UserName): User
  save(user: User): void
  delete(user: User): void
}
@enduml
