@startuml
class UserDeleteService {
  - userRepository: UserRepository
  + Delete(user User) error
}
class UserRegisterService {
  - userRepository: UserRepository
  - userService: UserService
  + Register(userName string) error
}
class UserGetService {
  - userRepository: UserRepository
  + Get(userName string) (*UserData, error)
}
class UserUpdateService {
  - userRepository: UserRepository
  - userService: UserService
  + Update(cmd UserUpdateCommand) error
}
@enduml
