@startuml
package Application {
  class UserApplicationService {
    - userRepository: UserRepository
  }

  interface UserRepository {
    FindByName(name UserName) (*User, error)
  }
}
note right
* インターフェースの主導権は上位レベルに持たせる
endnote

class MySQLUserRepository {
  - FindByName(name UserName) (*User, error)
}
note right
* 下位レベルが上位レベルに合わせる
endnote

UserRepository <|.. MySQLUserRepository
UserApplicationService .> UserRepository
@enduml
