@startuml
MySQLUserRepository ..|> UserRepository: インターフェースの実装(実現)は点線白矢印
class MySQLUserRepository {
  - FindByName(name UserName) (*User, error)
}
note right
MySQLUserRepositoryはUserRepositoryを実現(具現化)
endnote

interface UserRepository {
  FindByName(name UserName) (*User, error)
}
@enduml
