@startuml
UserRepository <|.. MySQLUserRepository
UserApplicationService .> UserRepository

interface UserRepository {
  FindByName(name UserName) (*User, error)
}
class UserApplicationService {
  - userRepository: UserRepository
}
class MySQLUserRepository {
  - FindByName(name UserName) (*User, error)
}
note as note
* MySQLUserRepositoryの**依存関係の矢印が逆転**
* データストアを変えた時の上位層は変えなくても良い
endnote
@enduml
