@startuml
UserRepository <|.. MySQLUserRepository
UserRepository <|..   UserFirebaseRepository
UserApplicationService .> UserRepository

interface UserRepository {
  FindByName(name UserName) (*User, error)
}
class UserApplicationService {
  - userRepository: UserRepository
}
class MySQLUserRepository {
  - FindByName(name UserName) (*User, error)
}
class UserFirebaseRepository {
  - FindByName(name UserName) (*User, error)
}
note as note
実現するオブジェクトはすぐ変更可能
endnote
@enduml
