@startuml
class Program {
  - serviceProvide: ServiceProvider
  + main()
  + run()
}
class IoC {
  + register()
  + resolve()
}

class UserRegisterCommand {
  + id string
  + name string
  + email string
}

class UserApplicationService {
  + Register(cmd UserRegisterCommand) error
}
Program --> IoC: 依存関係を登録、インスタンス取得
Program -> UserRegisterCommand: ユースケースに必要なデータオブジェクト作成(ユーザ情報登録に必要なデータ作成)
Program --> UserApplicationService: ユースケース実現(ユーザ登録処理)
@enduml
