@startuml
title サーバー起動時の依存関係登録

class Startup {
  + startup()
}
note top
* サーバー起動時の処理
* IoCコンテナの依存関係登録
endnote

class DependencySetupFactory {
  + CreateSetup() DependencySetup
}
note top
* IoC設定スクリプトを選択する
endnote

class SqlConnectionDependencySetup {
  + Run(container *dig.Container)
  - setupRepository(container *dig.Container)
  - setupApplicationServices(container *dig.Container)
  - setupDomainService(container *dig.Container)
}
note top
* IoC設定スクリプトの1つ
* 依存関係の登録
endnote

Startup x--> DependencySetupFactory
Startup x--> SqlConnectionDependencySetup
DependencySetupFactory x--> SqlConnectionDependencySetup
@enduml
