@startuml
title コントローラーとクライアントとアプリケーションサービスの関係

class UserController {
  + NewUserController(svc *UserApplicationService) *UserController
  + Register(w http.ResponseWriter, r *http.Request)
}
note top
* Controller
* クライアントとアプリケーションサービスの仲介
endnote

class UserRegisterCommand {
  + NewUserRegisterCommand(req UserPostRequestModel) UserRegisterCommand
}
note top
* コマンドオブジェクト
* ユーザ登録に必要なデータオブジェクト
endnote

class UserApplicationService {
  Register(cmd UserRegisterCommand) error
}
note top
* Model
* ユーザアプリケーションサービス
* ユーザ登録する処理
endnote

UserController --> UserRegisterCommand: クライアントからのデータよりユーザ登録に必要なデータ作成
UserController --> UserApplicationService: ユーザ登録
@enduml
