@startuml
title 集約を表すクラス図

class UserID {
  + value: string
}

class Circle {
  - circleName: CircleName
  - circleID: CircleID
  - members: UserID[]
  + ChangeName(name CircleName) error
  + Join(member User) error
}

class CircleName {
  + String() string
}
class CircleID {
  + String() string
}

note left
Circleの集約にはUserIDだけ含める
endnote

Circle *-- CircleID: コンポジション
Circle *-- CircleName: コンポジション
Circle o-- UserID: 集約
@enduml
