@startuml
interface CircleSpecification {
  IsSatisfiedBy(c Circle) bool
}
note right
interfaceを利用することで
さまざまな検索条件をCircleRepositoryを修正することなく
追加できる
endnote
class CircleRecommendSpecification {
  IsSatisfiedBy(c Circle) bool
}
class CircleNewCreateSpecification {
  IsSatisfiedBy(c Circle) bool
}
class CircleRepository {
  + Find(spec CircleSpecification) ([]*Circle, error)
}
CircleSpecification <|-- CircleRecommendSpecification
CircleSpecification <|-- CircleNewCreateSpecification
CircleRepository -> CircleSpecification: 利用
@enduml
